version: 1.0.{build}
image: Visual Studio 2019

only_commits:
  files:
    - docfx/**/*

build_script:
- cmd: git checkout master
- cmd: docfx\build-site.cmd

environment:
  access_token:
    secure: E5yLQIoD1jEQiCI/I46b+DJx9vr7bSgprLOt9tC9OjJK7je3m5HC/QmX3PaxFBPm

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "pauldendulk@gmail.com"
  - git config --global user.name "pauldendulk"
  - git add -A 
  - git commit -a -m "Generating site"
  - git push  