// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP008:Don't assign member with injected and created disposables.", Justification = "<Pending>", Scope = "member", Target = "~F:Mapsui.Providers.Shapefile.Indexing.QuadTree._child0")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.Indexing.QuadTree.FromFile(System.String)~Mapsui.Providers.Shapefile.Indexing.QuadTree")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.Indexing.QuadTree.SaveIndex(System.String)")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore created IDisposable.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.DbaseReader.GetSchemaTable~System.Data.DataTable")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP008:Don't assign member with injected and created disposables.", Justification = "<Pending>", Scope = "member", Target = "~F:Mapsui.Providers.Wfs.Utilities.GeometryFactory.XmlReader")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore created IDisposable.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wfs.Utilities.GeometryFactory.CreateReader(Mapsui.Providers.Wfs.Utilities.HttpClientUtil)")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP007:Don't dispose injected.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wfs.Xml.XPathQueryManager.InitializeXPathObjects(System.IO.Stream)")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wfs.WFSProvider.ExecuteIntersectionQuery(Mapsui.Geometries.BoundingBox)~System.Collections.Generic.IEnumerable{Mapsui.IFeature}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wms.Client.GetStreamAsync(System.String)~System.Threading.Tasks.Task{System.IO.Stream}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wms.GetFeatureInfo.GetStreamAsync(System.String)~System.Threading.Tasks.Task{System.IO.Stream}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wms.WmsProvider.GetFeatures(Mapsui.Layers.FetchInfo)~System.Collections.Generic.IEnumerable{Mapsui.IFeature}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Wms.WmsProvider.GetStreamAsync(System.String)~System.Threading.Tasks.Task{System.IO.Stream}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.ShapeFile.Open")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP008:Don't assign member with injected and created disposables.", Justification = "<Pending>", Scope = "member", Target = "~F:Mapsui.Providers.Shapefile.Indexing.QuadTree._child1")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.ShapeFile.GetGeometryPrivate(System.UInt32)~Mapsui.Geometries.IGeometry")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.ShapeFile.GetFeaturePrivate(System.UInt32,System.Collections.Generic.IEnumerable{Mapsui.GeometryLayer.GeometryFeature})~Mapsui.GeometryLayer.GeometryFeature")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.ShapeFile.GetFeatures(Mapsui.Layers.FetchInfo)~System.Collections.Generic.IEnumerable{Mapsui.GeometryLayer.GeometryFeature}")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Providers.Shapefile.ShapeFile.GetFeatures(Mapsui.Layers.FetchInfo)~System.Collections.Generic.IAsyncEnumerable{Mapsui.GeometryLayer.GeometryFeature}")]
